### ISSUE TITLE
 Realtime Point Cloud extraction 

### ISSUE THREAD

**Issue by nachovizzo** [Kin-Zhang/vdbfusion_mapping#1]
https://github.com/Kin-Zhang/vdbfusion_mapping/blob/754d5ff5b20729ccf78e281432576a802d44dbe5/vdbfusion_mapping/src/vdbfusion_mapper.cpp#L153

You can use the snippet provided by @mpottinger [here](https://github.com/PRBonn/vdbfusion/issues/22#issuecomment-1277093850) to do realtime point-cloud extraction, without having to mesh the VDB. I guess this can be much faster ;)

More info at https://github.com/PRBonn/vdbfusion/issues/22

**Comment by Kin-Zhang** [comment]
Thanks for the reminder! I will check and test on the speed

**Comment by Kin-Zhang** [comment]
Test about the mpottinger version, but switch to the @paucarre for color.

Done at the commit: https://github.com/Kin-Zhang/vdbfusion_mapping/commit/9e53c81cb120a147421e47a6eb8af35cc1644177

screenshot on the result (meshlab view): 
![image](https://user-images.githubusercontent.com/35365764/200626528-a657a0e6-2fca-48d7-8b34-d8619b6f33e8.png)

The mesh save or point extract is not running every step, it only happens when we run:
```bash
rosservice call /save_map '/home/kin/kin_vdbfusion_cow_test' 0.0
success: True
```

**Comment by nachovizzo** [comment]
Wow, that was fast!!!

**Comment by nachovizzo** [comment]
I added a bit more polished dockerized version of this repo here: https://github.com/nachovizzo/vdbfusion_mapping. In case you want to have a look. I just run your code in an Ubuntu 22.04 machine, and it's actually working. ;)

I did it just for the sake of fun, no need to take any particular action

**Comment by Kin-Zhang** [comment]
Ha, Thanks for letting me know, actually, there is the [Dockerfile](https://github.com/Kin-Zhang/vdbfusion_mapping/blob/master/Dockerfile) in the repo, and also one in dockerhub. 
Nice `ros_in_docker` try. Thanks!
